# Managed by Ordivon Operations v2: shared persistent PostgreSQL substrate.
[Service]
PIDFile=/var/lib/postgres/ordivon-data-r5-pg-14550-v4/postmaster.pid
ExecStartPre=
ExecStartPre=/usr/bin/postgresql-check-db-dir /var/lib/postgres/ordivon-data-r5-pg-14550-v4
ExecStart=
ExecStart=/usr/bin/postgres -D /var/lib/postgres/ordivon-data-r5-pg-14550-v4
