[ordivon]
pg1-path=/var/lib/postgres/ordivon-data-r5-pg-14550-v4
pg1-port=55434
pg1-socket-path=/var/lib/postgres/ordivon-data-r5-pg-14550-v4

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=7
start-fast=y
process-max=2
compress-type=zst
compress-level=3
log-path=/var/log/pgbackrest
